languages:
  en: English
  es: Español
  jp: 日本語
templates:
  - name: Chla
cores:
  - name: aen
    sheets:
      - name: occurrence
        required: [uuid, shipid, statid, eventDate, decimalLatitude, decimalLongitude]
        recommended: [shipid]
        grouping: [required, event, identification ]
        terms:
          required: [uuid, shipid, statid, eventDate, decimalLatitude, decimalLongitude]
          event: [ start_date, end_date,
            eventTime, start_time, end_time,
            depthInMeters, maximumDepthInMeters, minimumDepthInMeters]
          identification: [taxon, phylum, classify, order, family]
  - name: event
    sheets:
      - name: event
        required: [ eventID ]
      - name: occurrence
        required: [ occurrenceID, basisOfRecord, eventDate, scientificName ]
        recommended: [ occurrenceID, basisOfRecord, eventDate, kingdom, scientificName, taxonRank, decimalLatitude, decimalLongitude, geodeticDatum, coordinateUncertaintyInMeters, countryCode, individualCount, organismQuantity, organismQuantityType ]
        grouping: [ recordLevel, occurrence, event, location, identification, taxon, organism, other]
        terms:
          event: [eventID, parentEventID, fieldNumber, eventDate, eventTime, startDayOfYear,
            endDayOfYear, year, month, day, verbatimEventDate, habitat, samplingProtocol,
            sampleSizeValue, sampleSizeUnit, samplingEffort, fieldNotes, eventRemarks]
          identification: [identificationID, identificationQualifier, typeStatus, identifiedBy,
            dateIdentified, identificationReferences, identificationVerificationStatus, identificationRemarks]
          location: [locationID, higherGeographyID, higherGeography, continent, waterBody,
            islandGroup, island, country, countryCode, stateProvince, county, municipality,
            locality, verbatimLocality, minimumElevationInMeters, maximumElevationInMeters,
            verbatimElevation, minimumDepthInMeters, maximumDepthInMeters, verbatimDepth,
            minimumDistanceAboveSurfaceInMeters, maximumDistanceAboveSurfaceInMeters, locationAccordingTo,
            locationRemarks, decimalLatitude, decimalLongitude, geodeticDatum, coordinateUncertaintyInMeters,
            coordinatePrecision, pointRadiusSpatialFit, verbatimCoordinates, verbatimLatitude,
            verbatimLongitude, verbatimCoordinateSystem, verbatimSRS, footprintWKT, footprintSRS,
            footprintSpatialFit, georeferencedBy, georeferencedDate, georeferenceProtocol,
            georeferenceSources, georeferenceVerificationStatus, georeferenceRemarks]
          occurrence: [occurrenceID, catalogNumber, recordNumber, recordedBy, individualCount,
            organismQuantity, organismQuantityType, sex, lifeStage, reproductiveCondition,
            behavior, establishmentMeans, occurrenceStatus, preparations, disposition, associatedMedia,
            associatedReferences, associatedSequences, associatedTaxa, otherCatalogNumbers,
            occurrenceRemarks]
          organism: [organismID, organismName, organismScope, associatedOccurrences, associatedOrganisms,
            previousIdentifications, organismRemarks]
          other: [materialSampleID]
          recordLevel: [type, modified, language, license, rightsHolder, accessRights, bibliographicCitation,
            references, institutionID, collectionID, datasetID, institutionCode, collectionCode,
            datasetName, ownerInstitutionCode, basisOfRecord, informationWithheld, dataGeneralizations,
            dynamicProperties]
          taxon: [taxonID, scientificNameID, acceptedNameUsageID, parentNameUsageID, originalNameUsageID,
            nameAccordingToID, namePublishedInID, taxonConceptID, scientificName, acceptedNameUsage,
            parentNameUsage, originalNameUsage, nameAccordingTo, namePublishedIn, namePublishedInYear,
            higherClassification, kingdom, phylum, class, order, family, genus, subgenus,
            specificEpithet, infraspecificEpithet, taxonRank, verbatimTaxonRank, scientificNameAuthorship,
            vernacularName, nomenclaturalCode, taxonomicStatus, nomenclaturalStatus, taxonRemarks]

